- name: Upgrade packages
  apt:
    update_cache: yes
    upgrade: yes

- name: Install editors
  apt:
    name:
      - neovim
      - emacs
      - nano

- name: Install shells
  apt:
    name:
      - bash
      - zsh
      - fish

# - name: Install programming languages
